#!/usr/bin/env python3

import sys

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

def factorize_rsa_number(n):
    for i in range(2, n // 2 + 1):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            return i, n // i
    return n, 1

def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            try:
                n = int(line)
                p, q = factorize_rsa_number(n)
                print(f"{n}={p}*{q}")
            except ValueError:
                # Handle invalid input lines
                pass

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)

